// Code generated by ent, DO NOT EDIT.

package ent

import (
	"errors"
	"fmt"

	"github.com/open-boardgame-stats/backend/internal/ent/enums"
	"github.com/open-boardgame-stats/backend/internal/ent/game"
	"github.com/open-boardgame-stats/backend/internal/ent/gameversion"
	"github.com/open-boardgame-stats/backend/internal/ent/group"
	"github.com/open-boardgame-stats/backend/internal/ent/groupmembership"
	"github.com/open-boardgame-stats/backend/internal/ent/groupsettings"
	"github.com/open-boardgame-stats/backend/internal/ent/match"
	"github.com/open-boardgame-stats/backend/internal/ent/player"
	"github.com/open-boardgame-stats/backend/internal/ent/playersupervisionrequest"
	"github.com/open-boardgame-stats/backend/internal/ent/playersupervisionrequestapproval"
	"github.com/open-boardgame-stats/backend/internal/ent/predicate"
	"github.com/open-boardgame-stats/backend/internal/ent/schema/guidgql"
	"github.com/open-boardgame-stats/backend/internal/ent/user"
)

// GameWhereInput represents a where input for filtering Game queries.
type GameWhereInput struct {
	Predicates []predicate.Game  `json:"-"`
	Not        *GameWhereInput   `json:"not,omitempty"`
	Or         []*GameWhereInput `json:"or,omitempty"`
	And        []*GameWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "min_players" field predicates.
	MinPlayers      *int  `json:"minPlayers,omitempty"`
	MinPlayersNEQ   *int  `json:"minPlayersNEQ,omitempty"`
	MinPlayersIn    []int `json:"minPlayersIn,omitempty"`
	MinPlayersNotIn []int `json:"minPlayersNotIn,omitempty"`
	MinPlayersGT    *int  `json:"minPlayersGT,omitempty"`
	MinPlayersGTE   *int  `json:"minPlayersGTE,omitempty"`
	MinPlayersLT    *int  `json:"minPlayersLT,omitempty"`
	MinPlayersLTE   *int  `json:"minPlayersLTE,omitempty"`

	// "max_players" field predicates.
	MaxPlayers      *int  `json:"maxPlayers,omitempty"`
	MaxPlayersNEQ   *int  `json:"maxPlayersNEQ,omitempty"`
	MaxPlayersIn    []int `json:"maxPlayersIn,omitempty"`
	MaxPlayersNotIn []int `json:"maxPlayersNotIn,omitempty"`
	MaxPlayersGT    *int  `json:"maxPlayersGT,omitempty"`
	MaxPlayersGTE   *int  `json:"maxPlayersGTE,omitempty"`
	MaxPlayersLT    *int  `json:"maxPlayersLT,omitempty"`
	MaxPlayersLTE   *int  `json:"maxPlayersLTE,omitempty"`

	// "author" edge predicates.
	HasAuthor     *bool             `json:"hasAuthor,omitempty"`
	HasAuthorWith []*UserWhereInput `json:"hasAuthorWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *GameWhereInput) AddPredicates(predicates ...predicate.Game) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the GameWhereInput filter on the GameQuery builder.
func (i *GameWhereInput) Filter(q *GameQuery) (*GameQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyGameWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyGameWhereInput is returned in case the GameWhereInput is empty.
var ErrEmptyGameWhereInput = errors.New("ent: empty predicate GameWhereInput")

// P returns a predicate for filtering games.
// An error is returned if the input is empty or invalid.
func (i *GameWhereInput) P() (predicate.Game, error) {
	var predicates []predicate.Game
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, game.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Game, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, game.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Game, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, game.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, game.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, game.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, game.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, game.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, game.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, game.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, game.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, game.IDLTE(*i.IDLTE))
	}
	if i.Name != nil {
		predicates = append(predicates, game.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, game.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, game.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, game.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, game.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, game.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, game.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, game.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, game.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, game.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, game.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, game.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, game.NameContainsFold(*i.NameContainsFold))
	}
	if i.MinPlayers != nil {
		predicates = append(predicates, game.MinPlayersEQ(*i.MinPlayers))
	}
	if i.MinPlayersNEQ != nil {
		predicates = append(predicates, game.MinPlayersNEQ(*i.MinPlayersNEQ))
	}
	if len(i.MinPlayersIn) > 0 {
		predicates = append(predicates, game.MinPlayersIn(i.MinPlayersIn...))
	}
	if len(i.MinPlayersNotIn) > 0 {
		predicates = append(predicates, game.MinPlayersNotIn(i.MinPlayersNotIn...))
	}
	if i.MinPlayersGT != nil {
		predicates = append(predicates, game.MinPlayersGT(*i.MinPlayersGT))
	}
	if i.MinPlayersGTE != nil {
		predicates = append(predicates, game.MinPlayersGTE(*i.MinPlayersGTE))
	}
	if i.MinPlayersLT != nil {
		predicates = append(predicates, game.MinPlayersLT(*i.MinPlayersLT))
	}
	if i.MinPlayersLTE != nil {
		predicates = append(predicates, game.MinPlayersLTE(*i.MinPlayersLTE))
	}
	if i.MaxPlayers != nil {
		predicates = append(predicates, game.MaxPlayersEQ(*i.MaxPlayers))
	}
	if i.MaxPlayersNEQ != nil {
		predicates = append(predicates, game.MaxPlayersNEQ(*i.MaxPlayersNEQ))
	}
	if len(i.MaxPlayersIn) > 0 {
		predicates = append(predicates, game.MaxPlayersIn(i.MaxPlayersIn...))
	}
	if len(i.MaxPlayersNotIn) > 0 {
		predicates = append(predicates, game.MaxPlayersNotIn(i.MaxPlayersNotIn...))
	}
	if i.MaxPlayersGT != nil {
		predicates = append(predicates, game.MaxPlayersGT(*i.MaxPlayersGT))
	}
	if i.MaxPlayersGTE != nil {
		predicates = append(predicates, game.MaxPlayersGTE(*i.MaxPlayersGTE))
	}
	if i.MaxPlayersLT != nil {
		predicates = append(predicates, game.MaxPlayersLT(*i.MaxPlayersLT))
	}
	if i.MaxPlayersLTE != nil {
		predicates = append(predicates, game.MaxPlayersLTE(*i.MaxPlayersLTE))
	}

	if i.HasAuthor != nil {
		p := game.HasAuthor()
		if !*i.HasAuthor {
			p = game.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasAuthorWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasAuthorWith))
		for _, w := range i.HasAuthorWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasAuthorWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, game.HasAuthorWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyGameWhereInput
	case 1:
		return predicates[0], nil
	default:
		return game.And(predicates...), nil
	}
}

// GameVersionWhereInput represents a where input for filtering GameVersion queries.
type GameVersionWhereInput struct {
	Predicates []predicate.GameVersion  `json:"-"`
	Not        *GameVersionWhereInput   `json:"not,omitempty"`
	Or         []*GameVersionWhereInput `json:"or,omitempty"`
	And        []*GameVersionWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "version_number" field predicates.
	VersionNumber      *int  `json:"versionNumber,omitempty"`
	VersionNumberNEQ   *int  `json:"versionNumberNEQ,omitempty"`
	VersionNumberIn    []int `json:"versionNumberIn,omitempty"`
	VersionNumberNotIn []int `json:"versionNumberNotIn,omitempty"`
	VersionNumberGT    *int  `json:"versionNumberGT,omitempty"`
	VersionNumberGTE   *int  `json:"versionNumberGTE,omitempty"`
	VersionNumberLT    *int  `json:"versionNumberLT,omitempty"`
	VersionNumberLTE   *int  `json:"versionNumberLTE,omitempty"`

	// "game" edge predicates.
	HasGame     *bool             `json:"hasGame,omitempty"`
	HasGameWith []*GameWhereInput `json:"hasGameWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *GameVersionWhereInput) AddPredicates(predicates ...predicate.GameVersion) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the GameVersionWhereInput filter on the GameVersionQuery builder.
func (i *GameVersionWhereInput) Filter(q *GameVersionQuery) (*GameVersionQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyGameVersionWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyGameVersionWhereInput is returned in case the GameVersionWhereInput is empty.
var ErrEmptyGameVersionWhereInput = errors.New("ent: empty predicate GameVersionWhereInput")

// P returns a predicate for filtering gameversions.
// An error is returned if the input is empty or invalid.
func (i *GameVersionWhereInput) P() (predicate.GameVersion, error) {
	var predicates []predicate.GameVersion
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, gameversion.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.GameVersion, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, gameversion.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.GameVersion, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, gameversion.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, gameversion.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, gameversion.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, gameversion.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, gameversion.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, gameversion.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, gameversion.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, gameversion.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, gameversion.IDLTE(*i.IDLTE))
	}
	if i.VersionNumber != nil {
		predicates = append(predicates, gameversion.VersionNumberEQ(*i.VersionNumber))
	}
	if i.VersionNumberNEQ != nil {
		predicates = append(predicates, gameversion.VersionNumberNEQ(*i.VersionNumberNEQ))
	}
	if len(i.VersionNumberIn) > 0 {
		predicates = append(predicates, gameversion.VersionNumberIn(i.VersionNumberIn...))
	}
	if len(i.VersionNumberNotIn) > 0 {
		predicates = append(predicates, gameversion.VersionNumberNotIn(i.VersionNumberNotIn...))
	}
	if i.VersionNumberGT != nil {
		predicates = append(predicates, gameversion.VersionNumberGT(*i.VersionNumberGT))
	}
	if i.VersionNumberGTE != nil {
		predicates = append(predicates, gameversion.VersionNumberGTE(*i.VersionNumberGTE))
	}
	if i.VersionNumberLT != nil {
		predicates = append(predicates, gameversion.VersionNumberLT(*i.VersionNumberLT))
	}
	if i.VersionNumberLTE != nil {
		predicates = append(predicates, gameversion.VersionNumberLTE(*i.VersionNumberLTE))
	}

	if i.HasGame != nil {
		p := gameversion.HasGame()
		if !*i.HasGame {
			p = gameversion.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasGameWith) > 0 {
		with := make([]predicate.Game, 0, len(i.HasGameWith))
		for _, w := range i.HasGameWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasGameWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, gameversion.HasGameWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyGameVersionWhereInput
	case 1:
		return predicates[0], nil
	default:
		return gameversion.And(predicates...), nil
	}
}

// GroupWhereInput represents a where input for filtering Group queries.
type GroupWhereInput struct {
	Predicates []predicate.Group  `json:"-"`
	Not        *GroupWhereInput   `json:"not,omitempty"`
	Or         []*GroupWhereInput `json:"or,omitempty"`
	And        []*GroupWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "settings" edge predicates.
	HasSettings     *bool                      `json:"hasSettings,omitempty"`
	HasSettingsWith []*GroupSettingsWhereInput `json:"hasSettingsWith,omitempty"`

	// "members" edge predicates.
	HasMembers     *bool                        `json:"hasMembers,omitempty"`
	HasMembersWith []*GroupMembershipWhereInput `json:"hasMembersWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *GroupWhereInput) AddPredicates(predicates ...predicate.Group) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the GroupWhereInput filter on the GroupQuery builder.
func (i *GroupWhereInput) Filter(q *GroupQuery) (*GroupQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyGroupWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyGroupWhereInput is returned in case the GroupWhereInput is empty.
var ErrEmptyGroupWhereInput = errors.New("ent: empty predicate GroupWhereInput")

// P returns a predicate for filtering groups.
// An error is returned if the input is empty or invalid.
func (i *GroupWhereInput) P() (predicate.Group, error) {
	var predicates []predicate.Group
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, group.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Group, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, group.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Group, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, group.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, group.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, group.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, group.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, group.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, group.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, group.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, group.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, group.IDLTE(*i.IDLTE))
	}
	if i.Name != nil {
		predicates = append(predicates, group.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, group.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, group.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, group.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, group.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, group.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, group.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, group.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, group.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, group.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, group.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, group.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, group.NameContainsFold(*i.NameContainsFold))
	}

	if i.HasSettings != nil {
		p := group.HasSettings()
		if !*i.HasSettings {
			p = group.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasSettingsWith) > 0 {
		with := make([]predicate.GroupSettings, 0, len(i.HasSettingsWith))
		for _, w := range i.HasSettingsWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasSettingsWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, group.HasSettingsWith(with...))
	}
	if i.HasMembers != nil {
		p := group.HasMembers()
		if !*i.HasMembers {
			p = group.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasMembersWith) > 0 {
		with := make([]predicate.GroupMembership, 0, len(i.HasMembersWith))
		for _, w := range i.HasMembersWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasMembersWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, group.HasMembersWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyGroupWhereInput
	case 1:
		return predicates[0], nil
	default:
		return group.And(predicates...), nil
	}
}

// GroupMembershipWhereInput represents a where input for filtering GroupMembership queries.
type GroupMembershipWhereInput struct {
	Predicates []predicate.GroupMembership  `json:"-"`
	Not        *GroupMembershipWhereInput   `json:"not,omitempty"`
	Or         []*GroupMembershipWhereInput `json:"or,omitempty"`
	And        []*GroupMembershipWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "role" field predicates.
	Role      *enums.Role  `json:"role,omitempty"`
	RoleNEQ   *enums.Role  `json:"roleNEQ,omitempty"`
	RoleIn    []enums.Role `json:"roleIn,omitempty"`
	RoleNotIn []enums.Role `json:"roleNotIn,omitempty"`

	// "group" edge predicates.
	HasGroup     *bool              `json:"hasGroup,omitempty"`
	HasGroupWith []*GroupWhereInput `json:"hasGroupWith,omitempty"`

	// "user" edge predicates.
	HasUser     *bool             `json:"hasUser,omitempty"`
	HasUserWith []*UserWhereInput `json:"hasUserWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *GroupMembershipWhereInput) AddPredicates(predicates ...predicate.GroupMembership) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the GroupMembershipWhereInput filter on the GroupMembershipQuery builder.
func (i *GroupMembershipWhereInput) Filter(q *GroupMembershipQuery) (*GroupMembershipQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyGroupMembershipWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyGroupMembershipWhereInput is returned in case the GroupMembershipWhereInput is empty.
var ErrEmptyGroupMembershipWhereInput = errors.New("ent: empty predicate GroupMembershipWhereInput")

// P returns a predicate for filtering groupmemberships.
// An error is returned if the input is empty or invalid.
func (i *GroupMembershipWhereInput) P() (predicate.GroupMembership, error) {
	var predicates []predicate.GroupMembership
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, groupmembership.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.GroupMembership, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, groupmembership.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.GroupMembership, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, groupmembership.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, groupmembership.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, groupmembership.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, groupmembership.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, groupmembership.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, groupmembership.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, groupmembership.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, groupmembership.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, groupmembership.IDLTE(*i.IDLTE))
	}
	if i.Role != nil {
		predicates = append(predicates, groupmembership.RoleEQ(*i.Role))
	}
	if i.RoleNEQ != nil {
		predicates = append(predicates, groupmembership.RoleNEQ(*i.RoleNEQ))
	}
	if len(i.RoleIn) > 0 {
		predicates = append(predicates, groupmembership.RoleIn(i.RoleIn...))
	}
	if len(i.RoleNotIn) > 0 {
		predicates = append(predicates, groupmembership.RoleNotIn(i.RoleNotIn...))
	}

	if i.HasGroup != nil {
		p := groupmembership.HasGroup()
		if !*i.HasGroup {
			p = groupmembership.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasGroupWith) > 0 {
		with := make([]predicate.Group, 0, len(i.HasGroupWith))
		for _, w := range i.HasGroupWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasGroupWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, groupmembership.HasGroupWith(with...))
	}
	if i.HasUser != nil {
		p := groupmembership.HasUser()
		if !*i.HasUser {
			p = groupmembership.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasUserWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasUserWith))
		for _, w := range i.HasUserWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasUserWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, groupmembership.HasUserWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyGroupMembershipWhereInput
	case 1:
		return predicates[0], nil
	default:
		return groupmembership.And(predicates...), nil
	}
}

// GroupSettingsWhereInput represents a where input for filtering GroupSettings queries.
type GroupSettingsWhereInput struct {
	Predicates []predicate.GroupSettings  `json:"-"`
	Not        *GroupSettingsWhereInput   `json:"not,omitempty"`
	Or         []*GroupSettingsWhereInput `json:"or,omitempty"`
	And        []*GroupSettingsWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "visibility" field predicates.
	Visibility      *groupsettings.Visibility  `json:"visibility,omitempty"`
	VisibilityNEQ   *groupsettings.Visibility  `json:"visibilityNEQ,omitempty"`
	VisibilityIn    []groupsettings.Visibility `json:"visibilityIn,omitempty"`
	VisibilityNotIn []groupsettings.Visibility `json:"visibilityNotIn,omitempty"`

	// "join_policy" field predicates.
	JoinPolicy      *groupsettings.JoinPolicy  `json:"joinPolicy,omitempty"`
	JoinPolicyNEQ   *groupsettings.JoinPolicy  `json:"joinPolicyNEQ,omitempty"`
	JoinPolicyIn    []groupsettings.JoinPolicy `json:"joinPolicyIn,omitempty"`
	JoinPolicyNotIn []groupsettings.JoinPolicy `json:"joinPolicyNotIn,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *GroupSettingsWhereInput) AddPredicates(predicates ...predicate.GroupSettings) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the GroupSettingsWhereInput filter on the GroupSettingsQuery builder.
func (i *GroupSettingsWhereInput) Filter(q *GroupSettingsQuery) (*GroupSettingsQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyGroupSettingsWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyGroupSettingsWhereInput is returned in case the GroupSettingsWhereInput is empty.
var ErrEmptyGroupSettingsWhereInput = errors.New("ent: empty predicate GroupSettingsWhereInput")

// P returns a predicate for filtering groupsettingsslice.
// An error is returned if the input is empty or invalid.
func (i *GroupSettingsWhereInput) P() (predicate.GroupSettings, error) {
	var predicates []predicate.GroupSettings
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, groupsettings.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.GroupSettings, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, groupsettings.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.GroupSettings, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, groupsettings.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, groupsettings.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, groupsettings.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, groupsettings.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, groupsettings.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, groupsettings.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, groupsettings.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, groupsettings.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, groupsettings.IDLTE(*i.IDLTE))
	}
	if i.Visibility != nil {
		predicates = append(predicates, groupsettings.VisibilityEQ(*i.Visibility))
	}
	if i.VisibilityNEQ != nil {
		predicates = append(predicates, groupsettings.VisibilityNEQ(*i.VisibilityNEQ))
	}
	if len(i.VisibilityIn) > 0 {
		predicates = append(predicates, groupsettings.VisibilityIn(i.VisibilityIn...))
	}
	if len(i.VisibilityNotIn) > 0 {
		predicates = append(predicates, groupsettings.VisibilityNotIn(i.VisibilityNotIn...))
	}
	if i.JoinPolicy != nil {
		predicates = append(predicates, groupsettings.JoinPolicyEQ(*i.JoinPolicy))
	}
	if i.JoinPolicyNEQ != nil {
		predicates = append(predicates, groupsettings.JoinPolicyNEQ(*i.JoinPolicyNEQ))
	}
	if len(i.JoinPolicyIn) > 0 {
		predicates = append(predicates, groupsettings.JoinPolicyIn(i.JoinPolicyIn...))
	}
	if len(i.JoinPolicyNotIn) > 0 {
		predicates = append(predicates, groupsettings.JoinPolicyNotIn(i.JoinPolicyNotIn...))
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyGroupSettingsWhereInput
	case 1:
		return predicates[0], nil
	default:
		return groupsettings.And(predicates...), nil
	}
}

// MatchWhereInput represents a where input for filtering Match queries.
type MatchWhereInput struct {
	Predicates []predicate.Match  `json:"-"`
	Not        *MatchWhereInput   `json:"not,omitempty"`
	Or         []*MatchWhereInput `json:"or,omitempty"`
	And        []*MatchWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "game_version" edge predicates.
	HasGameVersion     *bool                    `json:"hasGameVersion,omitempty"`
	HasGameVersionWith []*GameVersionWhereInput `json:"hasGameVersionWith,omitempty"`

	// "players" edge predicates.
	HasPlayers     *bool               `json:"hasPlayers,omitempty"`
	HasPlayersWith []*PlayerWhereInput `json:"hasPlayersWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *MatchWhereInput) AddPredicates(predicates ...predicate.Match) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the MatchWhereInput filter on the MatchQuery builder.
func (i *MatchWhereInput) Filter(q *MatchQuery) (*MatchQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyMatchWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyMatchWhereInput is returned in case the MatchWhereInput is empty.
var ErrEmptyMatchWhereInput = errors.New("ent: empty predicate MatchWhereInput")

// P returns a predicate for filtering matches.
// An error is returned if the input is empty or invalid.
func (i *MatchWhereInput) P() (predicate.Match, error) {
	var predicates []predicate.Match
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, match.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Match, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, match.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Match, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, match.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, match.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, match.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, match.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, match.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, match.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, match.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, match.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, match.IDLTE(*i.IDLTE))
	}

	if i.HasGameVersion != nil {
		p := match.HasGameVersion()
		if !*i.HasGameVersion {
			p = match.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasGameVersionWith) > 0 {
		with := make([]predicate.GameVersion, 0, len(i.HasGameVersionWith))
		for _, w := range i.HasGameVersionWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasGameVersionWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, match.HasGameVersionWith(with...))
	}
	if i.HasPlayers != nil {
		p := match.HasPlayers()
		if !*i.HasPlayers {
			p = match.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasPlayersWith) > 0 {
		with := make([]predicate.Player, 0, len(i.HasPlayersWith))
		for _, w := range i.HasPlayersWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasPlayersWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, match.HasPlayersWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyMatchWhereInput
	case 1:
		return predicates[0], nil
	default:
		return match.And(predicates...), nil
	}
}

// PlayerWhereInput represents a where input for filtering Player queries.
type PlayerWhereInput struct {
	Predicates []predicate.Player  `json:"-"`
	Not        *PlayerWhereInput   `json:"not,omitempty"`
	Or         []*PlayerWhereInput `json:"or,omitempty"`
	And        []*PlayerWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "owner" edge predicates.
	HasOwner     *bool             `json:"hasOwner,omitempty"`
	HasOwnerWith []*UserWhereInput `json:"hasOwnerWith,omitempty"`

	// "supervisors" edge predicates.
	HasSupervisors     *bool             `json:"hasSupervisors,omitempty"`
	HasSupervisorsWith []*UserWhereInput `json:"hasSupervisorsWith,omitempty"`

	// "supervision_requests" edge predicates.
	HasSupervisionRequests     *bool                                 `json:"hasSupervisionRequests,omitempty"`
	HasSupervisionRequestsWith []*PlayerSupervisionRequestWhereInput `json:"hasSupervisionRequestsWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *PlayerWhereInput) AddPredicates(predicates ...predicate.Player) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the PlayerWhereInput filter on the PlayerQuery builder.
func (i *PlayerWhereInput) Filter(q *PlayerQuery) (*PlayerQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyPlayerWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyPlayerWhereInput is returned in case the PlayerWhereInput is empty.
var ErrEmptyPlayerWhereInput = errors.New("ent: empty predicate PlayerWhereInput")

// P returns a predicate for filtering players.
// An error is returned if the input is empty or invalid.
func (i *PlayerWhereInput) P() (predicate.Player, error) {
	var predicates []predicate.Player
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, player.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Player, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, player.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Player, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, player.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, player.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, player.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, player.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, player.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, player.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, player.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, player.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, player.IDLTE(*i.IDLTE))
	}
	if i.Name != nil {
		predicates = append(predicates, player.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, player.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, player.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, player.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, player.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, player.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, player.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, player.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, player.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, player.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, player.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, player.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, player.NameContainsFold(*i.NameContainsFold))
	}

	if i.HasOwner != nil {
		p := player.HasOwner()
		if !*i.HasOwner {
			p = player.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasOwnerWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasOwnerWith))
		for _, w := range i.HasOwnerWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasOwnerWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, player.HasOwnerWith(with...))
	}
	if i.HasSupervisors != nil {
		p := player.HasSupervisors()
		if !*i.HasSupervisors {
			p = player.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasSupervisorsWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasSupervisorsWith))
		for _, w := range i.HasSupervisorsWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasSupervisorsWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, player.HasSupervisorsWith(with...))
	}
	if i.HasSupervisionRequests != nil {
		p := player.HasSupervisionRequests()
		if !*i.HasSupervisionRequests {
			p = player.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasSupervisionRequestsWith) > 0 {
		with := make([]predicate.PlayerSupervisionRequest, 0, len(i.HasSupervisionRequestsWith))
		for _, w := range i.HasSupervisionRequestsWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasSupervisionRequestsWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, player.HasSupervisionRequestsWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyPlayerWhereInput
	case 1:
		return predicates[0], nil
	default:
		return player.And(predicates...), nil
	}
}

// PlayerSupervisionRequestWhereInput represents a where input for filtering PlayerSupervisionRequest queries.
type PlayerSupervisionRequestWhereInput struct {
	Predicates []predicate.PlayerSupervisionRequest  `json:"-"`
	Not        *PlayerSupervisionRequestWhereInput   `json:"not,omitempty"`
	Or         []*PlayerSupervisionRequestWhereInput `json:"or,omitempty"`
	And        []*PlayerSupervisionRequestWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "sender" edge predicates.
	HasSender     *bool             `json:"hasSender,omitempty"`
	HasSenderWith []*UserWhereInput `json:"hasSenderWith,omitempty"`

	// "player" edge predicates.
	HasPlayer     *bool               `json:"hasPlayer,omitempty"`
	HasPlayerWith []*PlayerWhereInput `json:"hasPlayerWith,omitempty"`

	// "approvals" edge predicates.
	HasApprovals     *bool                                         `json:"hasApprovals,omitempty"`
	HasApprovalsWith []*PlayerSupervisionRequestApprovalWhereInput `json:"hasApprovalsWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *PlayerSupervisionRequestWhereInput) AddPredicates(predicates ...predicate.PlayerSupervisionRequest) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the PlayerSupervisionRequestWhereInput filter on the PlayerSupervisionRequestQuery builder.
func (i *PlayerSupervisionRequestWhereInput) Filter(q *PlayerSupervisionRequestQuery) (*PlayerSupervisionRequestQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyPlayerSupervisionRequestWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyPlayerSupervisionRequestWhereInput is returned in case the PlayerSupervisionRequestWhereInput is empty.
var ErrEmptyPlayerSupervisionRequestWhereInput = errors.New("ent: empty predicate PlayerSupervisionRequestWhereInput")

// P returns a predicate for filtering playersupervisionrequests.
// An error is returned if the input is empty or invalid.
func (i *PlayerSupervisionRequestWhereInput) P() (predicate.PlayerSupervisionRequest, error) {
	var predicates []predicate.PlayerSupervisionRequest
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, playersupervisionrequest.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.PlayerSupervisionRequest, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, playersupervisionrequest.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.PlayerSupervisionRequest, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, playersupervisionrequest.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, playersupervisionrequest.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, playersupervisionrequest.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, playersupervisionrequest.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, playersupervisionrequest.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, playersupervisionrequest.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, playersupervisionrequest.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, playersupervisionrequest.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, playersupervisionrequest.IDLTE(*i.IDLTE))
	}

	if i.HasSender != nil {
		p := playersupervisionrequest.HasSender()
		if !*i.HasSender {
			p = playersupervisionrequest.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasSenderWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasSenderWith))
		for _, w := range i.HasSenderWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasSenderWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, playersupervisionrequest.HasSenderWith(with...))
	}
	if i.HasPlayer != nil {
		p := playersupervisionrequest.HasPlayer()
		if !*i.HasPlayer {
			p = playersupervisionrequest.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasPlayerWith) > 0 {
		with := make([]predicate.Player, 0, len(i.HasPlayerWith))
		for _, w := range i.HasPlayerWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasPlayerWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, playersupervisionrequest.HasPlayerWith(with...))
	}
	if i.HasApprovals != nil {
		p := playersupervisionrequest.HasApprovals()
		if !*i.HasApprovals {
			p = playersupervisionrequest.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasApprovalsWith) > 0 {
		with := make([]predicate.PlayerSupervisionRequestApproval, 0, len(i.HasApprovalsWith))
		for _, w := range i.HasApprovalsWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasApprovalsWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, playersupervisionrequest.HasApprovalsWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyPlayerSupervisionRequestWhereInput
	case 1:
		return predicates[0], nil
	default:
		return playersupervisionrequest.And(predicates...), nil
	}
}

// PlayerSupervisionRequestApprovalWhereInput represents a where input for filtering PlayerSupervisionRequestApproval queries.
type PlayerSupervisionRequestApprovalWhereInput struct {
	Predicates []predicate.PlayerSupervisionRequestApproval  `json:"-"`
	Not        *PlayerSupervisionRequestApprovalWhereInput   `json:"not,omitempty"`
	Or         []*PlayerSupervisionRequestApprovalWhereInput `json:"or,omitempty"`
	And        []*PlayerSupervisionRequestApprovalWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "approved" field predicates.
	Approved       *bool `json:"approved,omitempty"`
	ApprovedNEQ    *bool `json:"approvedNEQ,omitempty"`
	ApprovedIsNil  bool  `json:"approvedIsNil,omitempty"`
	ApprovedNotNil bool  `json:"approvedNotNil,omitempty"`

	// "approver" edge predicates.
	HasApprover     *bool             `json:"hasApprover,omitempty"`
	HasApproverWith []*UserWhereInput `json:"hasApproverWith,omitempty"`

	// "supervision_request" edge predicates.
	HasSupervisionRequest     *bool                                 `json:"hasSupervisionRequest,omitempty"`
	HasSupervisionRequestWith []*PlayerSupervisionRequestWhereInput `json:"hasSupervisionRequestWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *PlayerSupervisionRequestApprovalWhereInput) AddPredicates(predicates ...predicate.PlayerSupervisionRequestApproval) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the PlayerSupervisionRequestApprovalWhereInput filter on the PlayerSupervisionRequestApprovalQuery builder.
func (i *PlayerSupervisionRequestApprovalWhereInput) Filter(q *PlayerSupervisionRequestApprovalQuery) (*PlayerSupervisionRequestApprovalQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyPlayerSupervisionRequestApprovalWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyPlayerSupervisionRequestApprovalWhereInput is returned in case the PlayerSupervisionRequestApprovalWhereInput is empty.
var ErrEmptyPlayerSupervisionRequestApprovalWhereInput = errors.New("ent: empty predicate PlayerSupervisionRequestApprovalWhereInput")

// P returns a predicate for filtering playersupervisionrequestapprovals.
// An error is returned if the input is empty or invalid.
func (i *PlayerSupervisionRequestApprovalWhereInput) P() (predicate.PlayerSupervisionRequestApproval, error) {
	var predicates []predicate.PlayerSupervisionRequestApproval
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, playersupervisionrequestapproval.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.PlayerSupervisionRequestApproval, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, playersupervisionrequestapproval.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.PlayerSupervisionRequestApproval, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, playersupervisionrequestapproval.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, playersupervisionrequestapproval.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, playersupervisionrequestapproval.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, playersupervisionrequestapproval.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, playersupervisionrequestapproval.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, playersupervisionrequestapproval.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, playersupervisionrequestapproval.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, playersupervisionrequestapproval.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, playersupervisionrequestapproval.IDLTE(*i.IDLTE))
	}
	if i.Approved != nil {
		predicates = append(predicates, playersupervisionrequestapproval.ApprovedEQ(*i.Approved))
	}
	if i.ApprovedNEQ != nil {
		predicates = append(predicates, playersupervisionrequestapproval.ApprovedNEQ(*i.ApprovedNEQ))
	}
	if i.ApprovedIsNil {
		predicates = append(predicates, playersupervisionrequestapproval.ApprovedIsNil())
	}
	if i.ApprovedNotNil {
		predicates = append(predicates, playersupervisionrequestapproval.ApprovedNotNil())
	}

	if i.HasApprover != nil {
		p := playersupervisionrequestapproval.HasApprover()
		if !*i.HasApprover {
			p = playersupervisionrequestapproval.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasApproverWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasApproverWith))
		for _, w := range i.HasApproverWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasApproverWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, playersupervisionrequestapproval.HasApproverWith(with...))
	}
	if i.HasSupervisionRequest != nil {
		p := playersupervisionrequestapproval.HasSupervisionRequest()
		if !*i.HasSupervisionRequest {
			p = playersupervisionrequestapproval.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasSupervisionRequestWith) > 0 {
		with := make([]predicate.PlayerSupervisionRequest, 0, len(i.HasSupervisionRequestWith))
		for _, w := range i.HasSupervisionRequestWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasSupervisionRequestWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, playersupervisionrequestapproval.HasSupervisionRequestWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyPlayerSupervisionRequestApprovalWhereInput
	case 1:
		return predicates[0], nil
	default:
		return playersupervisionrequestapproval.And(predicates...), nil
	}
}

// UserWhereInput represents a where input for filtering User queries.
type UserWhereInput struct {
	Predicates []predicate.User  `json:"-"`
	Not        *UserWhereInput   `json:"not,omitempty"`
	Or         []*UserWhereInput `json:"or,omitempty"`
	And        []*UserWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *guidgql.GUID  `json:"id,omitempty"`
	IDNEQ   *guidgql.GUID  `json:"idNEQ,omitempty"`
	IDIn    []guidgql.GUID `json:"idIn,omitempty"`
	IDNotIn []guidgql.GUID `json:"idNotIn,omitempty"`
	IDGT    *guidgql.GUID  `json:"idGT,omitempty"`
	IDGTE   *guidgql.GUID  `json:"idGTE,omitempty"`
	IDLT    *guidgql.GUID  `json:"idLT,omitempty"`
	IDLTE   *guidgql.GUID  `json:"idLTE,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "email" field predicates.
	Email             *string  `json:"email,omitempty"`
	EmailNEQ          *string  `json:"emailNEQ,omitempty"`
	EmailIn           []string `json:"emailIn,omitempty"`
	EmailNotIn        []string `json:"emailNotIn,omitempty"`
	EmailGT           *string  `json:"emailGT,omitempty"`
	EmailGTE          *string  `json:"emailGTE,omitempty"`
	EmailLT           *string  `json:"emailLT,omitempty"`
	EmailLTE          *string  `json:"emailLTE,omitempty"`
	EmailContains     *string  `json:"emailContains,omitempty"`
	EmailHasPrefix    *string  `json:"emailHasPrefix,omitempty"`
	EmailHasSuffix    *string  `json:"emailHasSuffix,omitempty"`
	EmailEqualFold    *string  `json:"emailEqualFold,omitempty"`
	EmailContainsFold *string  `json:"emailContainsFold,omitempty"`

	// "players" edge predicates.
	HasPlayers     *bool               `json:"hasPlayers,omitempty"`
	HasPlayersWith []*PlayerWhereInput `json:"hasPlayersWith,omitempty"`

	// "main_player" edge predicates.
	HasMainPlayer     *bool               `json:"hasMainPlayer,omitempty"`
	HasMainPlayerWith []*PlayerWhereInput `json:"hasMainPlayerWith,omitempty"`

	// "group_memberships" edge predicates.
	HasGroupMemberships     *bool                        `json:"hasGroupMemberships,omitempty"`
	HasGroupMembershipsWith []*GroupMembershipWhereInput `json:"hasGroupMembershipsWith,omitempty"`

	// "games" edge predicates.
	HasGames     *bool             `json:"hasGames,omitempty"`
	HasGamesWith []*GameWhereInput `json:"hasGamesWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *UserWhereInput) AddPredicates(predicates ...predicate.User) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the UserWhereInput filter on the UserQuery builder.
func (i *UserWhereInput) Filter(q *UserQuery) (*UserQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyUserWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyUserWhereInput is returned in case the UserWhereInput is empty.
var ErrEmptyUserWhereInput = errors.New("ent: empty predicate UserWhereInput")

// P returns a predicate for filtering users.
// An error is returned if the input is empty or invalid.
func (i *UserWhereInput) P() (predicate.User, error) {
	var predicates []predicate.User
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, user.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.User, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, user.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.User, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, user.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, user.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, user.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, user.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, user.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, user.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, user.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, user.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, user.IDLTE(*i.IDLTE))
	}
	if i.Name != nil {
		predicates = append(predicates, user.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, user.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, user.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, user.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, user.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, user.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, user.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, user.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, user.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, user.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, user.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, user.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, user.NameContainsFold(*i.NameContainsFold))
	}
	if i.Email != nil {
		predicates = append(predicates, user.EmailEQ(*i.Email))
	}
	if i.EmailNEQ != nil {
		predicates = append(predicates, user.EmailNEQ(*i.EmailNEQ))
	}
	if len(i.EmailIn) > 0 {
		predicates = append(predicates, user.EmailIn(i.EmailIn...))
	}
	if len(i.EmailNotIn) > 0 {
		predicates = append(predicates, user.EmailNotIn(i.EmailNotIn...))
	}
	if i.EmailGT != nil {
		predicates = append(predicates, user.EmailGT(*i.EmailGT))
	}
	if i.EmailGTE != nil {
		predicates = append(predicates, user.EmailGTE(*i.EmailGTE))
	}
	if i.EmailLT != nil {
		predicates = append(predicates, user.EmailLT(*i.EmailLT))
	}
	if i.EmailLTE != nil {
		predicates = append(predicates, user.EmailLTE(*i.EmailLTE))
	}
	if i.EmailContains != nil {
		predicates = append(predicates, user.EmailContains(*i.EmailContains))
	}
	if i.EmailHasPrefix != nil {
		predicates = append(predicates, user.EmailHasPrefix(*i.EmailHasPrefix))
	}
	if i.EmailHasSuffix != nil {
		predicates = append(predicates, user.EmailHasSuffix(*i.EmailHasSuffix))
	}
	if i.EmailEqualFold != nil {
		predicates = append(predicates, user.EmailEqualFold(*i.EmailEqualFold))
	}
	if i.EmailContainsFold != nil {
		predicates = append(predicates, user.EmailContainsFold(*i.EmailContainsFold))
	}

	if i.HasPlayers != nil {
		p := user.HasPlayers()
		if !*i.HasPlayers {
			p = user.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasPlayersWith) > 0 {
		with := make([]predicate.Player, 0, len(i.HasPlayersWith))
		for _, w := range i.HasPlayersWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasPlayersWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, user.HasPlayersWith(with...))
	}
	if i.HasMainPlayer != nil {
		p := user.HasMainPlayer()
		if !*i.HasMainPlayer {
			p = user.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasMainPlayerWith) > 0 {
		with := make([]predicate.Player, 0, len(i.HasMainPlayerWith))
		for _, w := range i.HasMainPlayerWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasMainPlayerWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, user.HasMainPlayerWith(with...))
	}
	if i.HasGroupMemberships != nil {
		p := user.HasGroupMemberships()
		if !*i.HasGroupMemberships {
			p = user.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasGroupMembershipsWith) > 0 {
		with := make([]predicate.GroupMembership, 0, len(i.HasGroupMembershipsWith))
		for _, w := range i.HasGroupMembershipsWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasGroupMembershipsWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, user.HasGroupMembershipsWith(with...))
	}
	if i.HasGames != nil {
		p := user.HasGames()
		if !*i.HasGames {
			p = user.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasGamesWith) > 0 {
		with := make([]predicate.Game, 0, len(i.HasGamesWith))
		for _, w := range i.HasGamesWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasGamesWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, user.HasGamesWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyUserWhereInput
	case 1:
		return predicates[0], nil
	default:
		return user.And(predicates...), nil
	}
}
