// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-boardgame-stats/backend/internal/ent/groupmembershipapplication"
	"github.com/open-boardgame-stats/backend/internal/ent/predicate"
)

// GroupMembershipApplicationDelete is the builder for deleting a GroupMembershipApplication entity.
type GroupMembershipApplicationDelete struct {
	config
	hooks    []Hook
	mutation *GroupMembershipApplicationMutation
}

// Where appends a list predicates to the GroupMembershipApplicationDelete builder.
func (gmad *GroupMembershipApplicationDelete) Where(ps ...predicate.GroupMembershipApplication) *GroupMembershipApplicationDelete {
	gmad.mutation.Where(ps...)
	return gmad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gmad *GroupMembershipApplicationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gmad.sqlExec, gmad.mutation, gmad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gmad *GroupMembershipApplicationDelete) ExecX(ctx context.Context) int {
	n, err := gmad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gmad *GroupMembershipApplicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupmembershipapplication.Table, sqlgraph.NewFieldSpec(groupmembershipapplication.FieldID, field.TypeString))
	if ps := gmad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gmad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gmad.mutation.done = true
	return affected, err
}

// GroupMembershipApplicationDeleteOne is the builder for deleting a single GroupMembershipApplication entity.
type GroupMembershipApplicationDeleteOne struct {
	gmad *GroupMembershipApplicationDelete
}

// Where appends a list predicates to the GroupMembershipApplicationDelete builder.
func (gmado *GroupMembershipApplicationDeleteOne) Where(ps ...predicate.GroupMembershipApplication) *GroupMembershipApplicationDeleteOne {
	gmado.gmad.mutation.Where(ps...)
	return gmado
}

// Exec executes the deletion query.
func (gmado *GroupMembershipApplicationDeleteOne) Exec(ctx context.Context) error {
	n, err := gmado.gmad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupmembershipapplication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gmado *GroupMembershipApplicationDeleteOne) ExecX(ctx context.Context) {
	if err := gmado.Exec(ctx); err != nil {
		panic(err)
	}
}
