// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-boardgame-stats/backend/internal/ent/group"
	"github.com/open-boardgame-stats/backend/internal/ent/groupmembershipapplication"
	"github.com/open-boardgame-stats/backend/internal/ent/schema/guidgql"
	"github.com/open-boardgame-stats/backend/internal/ent/user"
)

// GroupMembershipApplicationCreate is the builder for creating a GroupMembershipApplication entity.
type GroupMembershipApplicationCreate struct {
	config
	mutation *GroupMembershipApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMessage sets the "message" field.
func (gmac *GroupMembershipApplicationCreate) SetMessage(s string) *GroupMembershipApplicationCreate {
	gmac.mutation.SetMessage(s)
	return gmac
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (gmac *GroupMembershipApplicationCreate) SetNillableMessage(s *string) *GroupMembershipApplicationCreate {
	if s != nil {
		gmac.SetMessage(*s)
	}
	return gmac
}

// SetID sets the "id" field.
func (gmac *GroupMembershipApplicationCreate) SetID(gu guidgql.GUID) *GroupMembershipApplicationCreate {
	gmac.mutation.SetID(gu)
	return gmac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (gmac *GroupMembershipApplicationCreate) SetNillableID(gu *guidgql.GUID) *GroupMembershipApplicationCreate {
	if gu != nil {
		gmac.SetID(*gu)
	}
	return gmac
}

// SetUserID sets the "user" edge to the User entity by ID.
func (gmac *GroupMembershipApplicationCreate) SetUserID(id guidgql.GUID) *GroupMembershipApplicationCreate {
	gmac.mutation.SetUserID(id)
	return gmac
}

// SetUser sets the "user" edge to the User entity.
func (gmac *GroupMembershipApplicationCreate) SetUser(u *User) *GroupMembershipApplicationCreate {
	return gmac.SetUserID(u.ID)
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (gmac *GroupMembershipApplicationCreate) SetGroupID(id guidgql.GUID) *GroupMembershipApplicationCreate {
	gmac.mutation.SetGroupID(id)
	return gmac
}

// SetGroup sets the "group" edge to the Group entity.
func (gmac *GroupMembershipApplicationCreate) SetGroup(g *Group) *GroupMembershipApplicationCreate {
	return gmac.SetGroupID(g.ID)
}

// Mutation returns the GroupMembershipApplicationMutation object of the builder.
func (gmac *GroupMembershipApplicationCreate) Mutation() *GroupMembershipApplicationMutation {
	return gmac.mutation
}

// Save creates the GroupMembershipApplication in the database.
func (gmac *GroupMembershipApplicationCreate) Save(ctx context.Context) (*GroupMembershipApplication, error) {
	gmac.defaults()
	return withHooks(ctx, gmac.sqlSave, gmac.mutation, gmac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gmac *GroupMembershipApplicationCreate) SaveX(ctx context.Context) *GroupMembershipApplication {
	v, err := gmac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gmac *GroupMembershipApplicationCreate) Exec(ctx context.Context) error {
	_, err := gmac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmac *GroupMembershipApplicationCreate) ExecX(ctx context.Context) {
	if err := gmac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gmac *GroupMembershipApplicationCreate) defaults() {
	if _, ok := gmac.mutation.Message(); !ok {
		v := groupmembershipapplication.DefaultMessage
		gmac.mutation.SetMessage(v)
	}
	if _, ok := gmac.mutation.ID(); !ok {
		v := groupmembershipapplication.DefaultID()
		gmac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gmac *GroupMembershipApplicationCreate) check() error {
	if _, ok := gmac.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "GroupMembershipApplication.message"`)}
	}
	if _, ok := gmac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "GroupMembershipApplication.user"`)}
	}
	if _, ok := gmac.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupMembershipApplication.group"`)}
	}
	return nil
}

func (gmac *GroupMembershipApplicationCreate) sqlSave(ctx context.Context) (*GroupMembershipApplication, error) {
	if err := gmac.check(); err != nil {
		return nil, err
	}
	_node, _spec := gmac.createSpec()
	if err := sqlgraph.CreateNode(ctx, gmac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*guidgql.GUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	gmac.mutation.id = &_node.ID
	gmac.mutation.done = true
	return _node, nil
}

func (gmac *GroupMembershipApplicationCreate) createSpec() (*GroupMembershipApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupMembershipApplication{config: gmac.config}
		_spec = sqlgraph.NewCreateSpec(groupmembershipapplication.Table, sqlgraph.NewFieldSpec(groupmembershipapplication.FieldID, field.TypeString))
	)
	_spec.OnConflict = gmac.conflict
	if id, ok := gmac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := gmac.mutation.Message(); ok {
		_spec.SetField(groupmembershipapplication.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if nodes := gmac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmembershipapplication.UserTable,
			Columns: []string{groupmembershipapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_group_membership_applications = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := gmac.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmembershipapplication.GroupTable,
			Columns: []string{groupmembershipapplication.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_applications = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupMembershipApplication.Create().
//		SetMessage(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupMembershipApplicationUpsert) {
//			SetMessage(v+v).
//		}).
//		Exec(ctx)
func (gmac *GroupMembershipApplicationCreate) OnConflict(opts ...sql.ConflictOption) *GroupMembershipApplicationUpsertOne {
	gmac.conflict = opts
	return &GroupMembershipApplicationUpsertOne{
		create: gmac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupMembershipApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (gmac *GroupMembershipApplicationCreate) OnConflictColumns(columns ...string) *GroupMembershipApplicationUpsertOne {
	gmac.conflict = append(gmac.conflict, sql.ConflictColumns(columns...))
	return &GroupMembershipApplicationUpsertOne{
		create: gmac,
	}
}

type (
	// GroupMembershipApplicationUpsertOne is the builder for "upsert"-ing
	//  one GroupMembershipApplication node.
	GroupMembershipApplicationUpsertOne struct {
		create *GroupMembershipApplicationCreate
	}

	// GroupMembershipApplicationUpsert is the "OnConflict" setter.
	GroupMembershipApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetMessage sets the "message" field.
func (u *GroupMembershipApplicationUpsert) SetMessage(v string) *GroupMembershipApplicationUpsert {
	u.Set(groupmembershipapplication.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *GroupMembershipApplicationUpsert) UpdateMessage() *GroupMembershipApplicationUpsert {
	u.SetExcluded(groupmembershipapplication.FieldMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GroupMembershipApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(groupmembershipapplication.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GroupMembershipApplicationUpsertOne) UpdateNewValues() *GroupMembershipApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(groupmembershipapplication.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupMembershipApplication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupMembershipApplicationUpsertOne) Ignore() *GroupMembershipApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupMembershipApplicationUpsertOne) DoNothing() *GroupMembershipApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupMembershipApplicationCreate.OnConflict
// documentation for more info.
func (u *GroupMembershipApplicationUpsertOne) Update(set func(*GroupMembershipApplicationUpsert)) *GroupMembershipApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupMembershipApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessage sets the "message" field.
func (u *GroupMembershipApplicationUpsertOne) SetMessage(v string) *GroupMembershipApplicationUpsertOne {
	return u.Update(func(s *GroupMembershipApplicationUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *GroupMembershipApplicationUpsertOne) UpdateMessage() *GroupMembershipApplicationUpsertOne {
	return u.Update(func(s *GroupMembershipApplicationUpsert) {
		s.UpdateMessage()
	})
}

// Exec executes the query.
func (u *GroupMembershipApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupMembershipApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupMembershipApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupMembershipApplicationUpsertOne) ID(ctx context.Context) (id guidgql.GUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GroupMembershipApplicationUpsertOne.ID is not supported by MySQL driver. Use GroupMembershipApplicationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupMembershipApplicationUpsertOne) IDX(ctx context.Context) guidgql.GUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupMembershipApplicationCreateBulk is the builder for creating many GroupMembershipApplication entities in bulk.
type GroupMembershipApplicationCreateBulk struct {
	config
	builders []*GroupMembershipApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupMembershipApplication entities in the database.
func (gmacb *GroupMembershipApplicationCreateBulk) Save(ctx context.Context) ([]*GroupMembershipApplication, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gmacb.builders))
	nodes := make([]*GroupMembershipApplication, len(gmacb.builders))
	mutators := make([]Mutator, len(gmacb.builders))
	for i := range gmacb.builders {
		func(i int, root context.Context) {
			builder := gmacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMembershipApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gmacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = gmacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gmacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gmacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gmacb *GroupMembershipApplicationCreateBulk) SaveX(ctx context.Context) []*GroupMembershipApplication {
	v, err := gmacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gmacb *GroupMembershipApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := gmacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmacb *GroupMembershipApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := gmacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupMembershipApplication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupMembershipApplicationUpsert) {
//			SetMessage(v+v).
//		}).
//		Exec(ctx)
func (gmacb *GroupMembershipApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupMembershipApplicationUpsertBulk {
	gmacb.conflict = opts
	return &GroupMembershipApplicationUpsertBulk{
		create: gmacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupMembershipApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (gmacb *GroupMembershipApplicationCreateBulk) OnConflictColumns(columns ...string) *GroupMembershipApplicationUpsertBulk {
	gmacb.conflict = append(gmacb.conflict, sql.ConflictColumns(columns...))
	return &GroupMembershipApplicationUpsertBulk{
		create: gmacb,
	}
}

// GroupMembershipApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupMembershipApplication nodes.
type GroupMembershipApplicationUpsertBulk struct {
	create *GroupMembershipApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupMembershipApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(groupmembershipapplication.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GroupMembershipApplicationUpsertBulk) UpdateNewValues() *GroupMembershipApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(groupmembershipapplication.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupMembershipApplication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupMembershipApplicationUpsertBulk) Ignore() *GroupMembershipApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupMembershipApplicationUpsertBulk) DoNothing() *GroupMembershipApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupMembershipApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *GroupMembershipApplicationUpsertBulk) Update(set func(*GroupMembershipApplicationUpsert)) *GroupMembershipApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupMembershipApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessage sets the "message" field.
func (u *GroupMembershipApplicationUpsertBulk) SetMessage(v string) *GroupMembershipApplicationUpsertBulk {
	return u.Update(func(s *GroupMembershipApplicationUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *GroupMembershipApplicationUpsertBulk) UpdateMessage() *GroupMembershipApplicationUpsertBulk {
	return u.Update(func(s *GroupMembershipApplicationUpsert) {
		s.UpdateMessage()
	})
}

// Exec executes the query.
func (u *GroupMembershipApplicationUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupMembershipApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupMembershipApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupMembershipApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
