// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/open-boardgame-stats/backend/internal/ent/group"
	"github.com/open-boardgame-stats/backend/internal/ent/groupsettings"
	"github.com/open-boardgame-stats/backend/internal/ent/schema/guidgql"
)

// Group is the model entity for the Group schema.
type Group struct {
	config `json:"-"`
	// ID of the ent.
	ID guidgql.GUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// LogoURL holds the value of the "logo_url" field.
	LogoURL string `json:"logo_url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupQuery when eager-loading is set.
	Edges        GroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupEdges holds the relations/edges for other nodes in the graph.
type GroupEdges struct {
	// Settings holds the value of the settings edge.
	Settings *GroupSettings `json:"settings,omitempty"`
	// Members holds the value of the members edge.
	Members []*GroupMembership `json:"members,omitempty"`
	// Applications holds the value of the applications edge.
	Applications []*GroupMembershipApplication `json:"applications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int

	namedMembers      map[string][]*GroupMembership
	namedApplications map[string][]*GroupMembershipApplication
}

// SettingsOrErr returns the Settings value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupEdges) SettingsOrErr() (*GroupSettings, error) {
	if e.loadedTypes[0] {
		if e.Settings == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: groupsettings.Label}
		}
		return e.Settings, nil
	}
	return nil, &NotLoadedError{edge: "settings"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) MembersOrErr() ([]*GroupMembership, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// ApplicationsOrErr returns the Applications value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) ApplicationsOrErr() ([]*GroupMembershipApplication, error) {
	if e.loadedTypes[2] {
		return e.Applications, nil
	}
	return nil, &NotLoadedError{edge: "applications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Group) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			values[i] = new(guidgql.GUID)
		case group.FieldName, group.FieldDescription, group.FieldLogoURL:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Group fields.
func (gr *Group) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			if value, ok := values[i].(*guidgql.GUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				gr.ID = *value
			}
		case group.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				gr.Name = value.String
			}
		case group.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				gr.Description = value.String
			}
		case group.FieldLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_url", values[i])
			} else if value.Valid {
				gr.LogoURL = value.String
			}
		default:
			gr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Group.
// This includes values selected through modifiers, order, etc.
func (gr *Group) Value(name string) (ent.Value, error) {
	return gr.selectValues.Get(name)
}

// QuerySettings queries the "settings" edge of the Group entity.
func (gr *Group) QuerySettings() *GroupSettingsQuery {
	return NewGroupClient(gr.config).QuerySettings(gr)
}

// QueryMembers queries the "members" edge of the Group entity.
func (gr *Group) QueryMembers() *GroupMembershipQuery {
	return NewGroupClient(gr.config).QueryMembers(gr)
}

// QueryApplications queries the "applications" edge of the Group entity.
func (gr *Group) QueryApplications() *GroupMembershipApplicationQuery {
	return NewGroupClient(gr.config).QueryApplications(gr)
}

// Update returns a builder for updating this Group.
// Note that you need to call Group.Unwrap() before calling this method if this Group
// was returned from a transaction, and the transaction was committed or rolled back.
func (gr *Group) Update() *GroupUpdateOne {
	return NewGroupClient(gr.config).UpdateOne(gr)
}

// Unwrap unwraps the Group entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gr *Group) Unwrap() *Group {
	_tx, ok := gr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Group is not a transactional entity")
	}
	gr.config.driver = _tx.drv
	return gr
}

// String implements the fmt.Stringer.
func (gr *Group) String() string {
	var builder strings.Builder
	builder.WriteString("Group(")
	builder.WriteString(fmt.Sprintf("id=%v, ", gr.ID))
	builder.WriteString("name=")
	builder.WriteString(gr.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(gr.Description)
	builder.WriteString(", ")
	builder.WriteString("logo_url=")
	builder.WriteString(gr.LogoURL)
	builder.WriteByte(')')
	return builder.String()
}

// NamedMembers returns the Members named value or an error if the edge was not
// loaded in eager-loading with this name.
func (gr *Group) NamedMembers(name string) ([]*GroupMembership, error) {
	if gr.Edges.namedMembers == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := gr.Edges.namedMembers[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (gr *Group) appendNamedMembers(name string, edges ...*GroupMembership) {
	if gr.Edges.namedMembers == nil {
		gr.Edges.namedMembers = make(map[string][]*GroupMembership)
	}
	if len(edges) == 0 {
		gr.Edges.namedMembers[name] = []*GroupMembership{}
	} else {
		gr.Edges.namedMembers[name] = append(gr.Edges.namedMembers[name], edges...)
	}
}

// NamedApplications returns the Applications named value or an error if the edge was not
// loaded in eager-loading with this name.
func (gr *Group) NamedApplications(name string) ([]*GroupMembershipApplication, error) {
	if gr.Edges.namedApplications == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := gr.Edges.namedApplications[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (gr *Group) appendNamedApplications(name string, edges ...*GroupMembershipApplication) {
	if gr.Edges.namedApplications == nil {
		gr.Edges.namedApplications = make(map[string][]*GroupMembershipApplication)
	}
	if len(edges) == 0 {
		gr.Edges.namedApplications[name] = []*GroupMembershipApplication{}
	} else {
		gr.Edges.namedApplications[name] = append(gr.Edges.namedApplications[name], edges...)
	}
}

// Groups is a parsable slice of Group.
type Groups []*Group
